name: Test

on:
  push:
    branches:
      - '**'


jobs:
  reusable_workflow_job:
    uses: ./.github/workflows/reusable-test.yml
    name: Reusable test workflow

  another:
    uses: ./.github/workflows/another.yml
    name: Reusable test workflow
    with:
        input: "This is a Test"

  composite:
    uses: ./.github/workflows/composite
    name: composite workflow
    with:
        username: "This is a Test"